### ISSUE TITLE
Error sir!

### ISSUE THREAD

**Issue by haritsrm** [hilmysyarif/sms_gateway#1]
Error during invoke gem generator, I'd : 
* add new gem into +Gemfile+

>gem "sms_gateway", '0.3.0', github:'hilmysyarif/sms_gateway', branch: 'master'

* then I run +bundle install+
* for doing invoke, I run +rails g SmsGateway::Utilities.install+ and error :(

the error is : 

> Could not find generator 'sms_gateway:install'. Maybe you meant 'system_test', 'generator' or 'scss:assets'

**Comment by haritsrm** [comment]
sorry the error is : 

> Could not find generator 'SmsGateway::Utilities.install'. Maybe you meant 'test_unit:system', 'integration_test' or 'test_unit:integration'

**Comment by hilmysyarif** [comment]
@rietzche Thanks for your report, this generator command is running under rails console.
so, you must open rails console first.


Thanks.

**Comment by haritsrm** [comment]
thx sir. it's running now 👍

**Comment by nurfiagnia** [comment]
I have an error : 

> Failed to open TCP connection to smsgateway.me:443 (getaddrinfo: No such host is known. )

My code was : 

>   def sendd
>    m = SmsGateway::Sms.new(number: (params[:notlp]), message: (params[:isisms]), device: '69200')
>    if m.deliver
>     flash[:success] = "Sms sedang diproses"
>     redirect_to pengasuhan_mail_path
>  else

**Comment by hilmysyarif** [comment]
@nurfiagnia you must connect to internet and sure your device is connected to the internet too

**Comment by haritsrm** [comment]
How about SSL error, i found `OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed`
